# Generated by Django 4.2.11 on 2024-03-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.CharField(max_length=30)),
                ('average_score', models.IntegerField()),
                ('transfers_made', models.IntegerField()),
            ],
        ),
    ]
