# Generated by Django 4.2.11 on 2024-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0004_event_fixture_team_remove_player_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
