# Generated by Django 4.2.11 on 2024-03-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0007_remove_player_last_name_player_assists_player_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='Team',
        ),
    ]
