# Generated by Django 4.2.11 on 2024-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0008_rename_team_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Team',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
