# Generated by Django 4.2.11 on 2024-03-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0009_remove_player_team_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='club',
        ),
    ]
