# Generated by Django 4.2.11 on 2024-03-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0016_event_name_alter_fplmanager_players_pointsinfixture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='fpl_id',
        ),
    ]
