# Generated by Django 4.2.11 on 2024-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0017_rename_player_id_player_fpl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fpl_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
