# Generated by Django 4.2.11 on 2024-03-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0018_event_fpl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fplmanager',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pointsinfixture',
            unique_together={('player', 'fixture')},
        ),
    ]
