# Generated by Django 4.2.11 on 2024-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0019_remove_fplmanager_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='club',
            new_name='team',
        ),
    ]
