# Generated by Django 4.2.11 on 2024-03-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0022_fixture_team_a_team_h_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='fpl_id',
            new_name='fixture_id',
        ),
    ]
