# Generated by Django 4.2.11 on 2024-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0026_rename_team_a_team_h_difficulty_fixture_team_a_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_a_difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_a_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_h_difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_h_score',
            field=models.IntegerField(null=True),
        ),
    ]
