# Generated by Django 4.2.11 on 2024-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0027_alter_fixture_team_a_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsinfixture',
            name='fixture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pointsinfixture',
            name='player',
            field=models.IntegerField(),
        ),
    ]
