# Generated by Django 4.2.11 on 2024-03-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0029_alter_pointsinfixture_actual_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='fixture_id',
            new_name='fpl_id',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='fpl.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_h', to='fpl.team'),
        ),
        migrations.AlterField(
            model_name='pointsinfixture',
            name='actual_points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointsinfixture',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.fixture'),
        ),
        migrations.AlterField(
            model_name='pointsinfixture',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.player'),
        ),
        migrations.AlterField(
            model_name='pointsinfixture',
            name='predicted_points',
            field=models.FloatField(),
        ),
    ]
