# Generated by Django 4.2.11 on 2024-03-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0031_alter_pointsinfixture_actual_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fpl_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='fpl_id',
            field=models.IntegerField(unique=True),
        ),
    ]
