# Generated by Django 4.2.11 on 2024-04-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0033_alter_player_assists_alter_player_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fpl.event'),
            preserve_default=False,
        ),
    ]
